# Generated by Django 5.1.3 on 2024-11-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vase',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
