# Generated by Django 5.1.3 on 2024-11-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomboard', '0002_vase_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbprofile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
