# Generated by Django 5.1.3 on 2024-12-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomboard', '0003_alter_bbprofile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occassion', models.TextField(blank=True)),
                ('image', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomboard.bbprofile')),
                ('vase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomboard.vase')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloomboard.arrangement'),
        ),
        migrations.CreateModel(
            name='FlowerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_usages', to='bloomboard.arrangement')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomboard.flower')),
            ],
        ),
    ]
