# Generated by Django 5.1.3 on 2024-12-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloomboard', '0005_arrangement_type_alter_arrangement_vase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='vase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloomboard.vase'),
        ),
    ]
